name: âš™ï¸ Build Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Cargo Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: 'ğŸ“¥ Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'ğŸ¦€ Install Rust Toolchain'
        uses: dtolnay/rust-toolchain@stable

      - name: 'ğŸ“¦ Install Dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install -y gdb-multiarch

      - name: 'ğŸ”¨ Build'
        run: cargo build --verbose --examples

      - name: 'âœ¨ Format'
        run: cargo fmt --check

      - name: 'ğŸ“ Lint'
        run: cargo clippy --verbose --examples

      - name: 'ğŸ§ª Test'
        run: cargo test --verbose --examples

      - name: 'ğŸ”– Release'
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_RELEASE_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
